### ISSUE TITLE
AssaultCube Overlay doesn't display properly

### ISSUE THREAD

**Issue by dom0ng** [isabellaflores/assaultcube-overlay#1]
Sample overlay works fine on my machine (VM setup)

But assaultcube-overlay only put a little 1x1 overlay on top left of my screen.

Anyone have success trying this?
Anyone is using Vamos on a daily basis? 
Looking to find someone to buy more overlay.

Have a nice day

**Comment by isabellaflores** [comment]
Inside Vamos, go to Edit -> Target Display, and click on a monitor... That will choose the area for the overlay. Let me know if it helps?

**Comment by isabellaflores** [comment]
Inside Vamos, go to Edit -> Target Display, and click on a monitor... That will choose the area for the overlay. Let me know if it helps?

**Comment by dom0ng** [comment]
> Inside Vamos, go to Edit -> Target Display, and click on a monitor... That will choose the area for the overlay. Let me know if it helps? And while I encourage people to write their own overlays using Vamos, I only personally provide the overlay for AssaultCube.

Hello iflores
I am still learning Java, it’s not my main language, so that would take me few weeks to write and paste my own stuff.

Inside Vamos, and with Assault Cube Overlay, target display -> and choose the area didn’t help. 
I have a 2 screen setup and it display a little 1x1 overlay on top left of my main screen.
Even if I choose the second monitor, the 1x1 pixel only show on my first monitor.
I’m gonna post some picture later to illustrate


The sample overlay works fine tho, I can choose the monitor and area and it display perfectly. 

Have a nice day and thanks for the release, cool project

**Comment by isabellaflores** [comment]
It's probably not reading the window dimensions properly from AssaultCube... It's possible the memory location changed, I'll have to download the latest AssaultCube and see if they changed it.

**Comment by isabellaflores** [comment]
Can you try with the previous version of AssaultCube v1.3.0.1 and see if it fixes the problem? https://github.com/assaultcube/AC/releases/tag/v1.3.0.1

**Comment by isabellaflores** [comment]
I reproduced the issue. I'm looking into it. Thank you.

**Comment by isabellaflores** [comment]
It appears that there have been 2 releases of AssaultCube since I designed the overlay... Can you try using AssaultCube v1.3.0.0 Lockdown Edition? https://github.com/assaultcube/AC/releases/tag/v1.3.0.0

**Comment by dom0ng** [comment]
> It appears that there have been 2 releases of AssaultCube since I designed the overlay... Can you try using AssaultCube v1.3.0.0 Lockdown Edition? https://github.com/assaultcube/AC/releases/tag/v1.3.0.0

Hello iflores !

It is working fine with v1.3.0.0 Lockdown Edition !

Thanks a lot !

**Comment by isabellaflores** [comment]
Fabulous. I'm glad that was the only problem. The AssaultCube overlay is really just meant as an example of how to write overlays for overlay authors, rather than a true product that is meant to be used. It's expected that memory locations will change from release to release of a game, and it's up to the overlay author to keep up with or mitigate those changes, which I haven't done with the AssaultCube overlay unfortunately. Please feel free to write me at isabella99flores@gmail.com if you are interested in using Vamos to create an overlay and have any questions about Vamos or Java, and I'll do my best to help.
